# -*- coding: utf-8 -*-
"""involuta de la cicloide otra cicloide.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ERt_1_nbySkHnUq1QiCBtzJd1Sg2MJnP
"""

import numpy as np
import matplotlib.pyplot as plt


r = 1

# cicloide
t = np.linspace(0, 3 * np.pi, 1000)
x_cycloid = r * (t - np.sin(t))
y_cycloid = r * (1 - np.cos(t))

# cicloide 2
t2 = np.linspace(0, 3 * np.pi, 1000)
x_involute_cycloid = r * (t2 - np.sin(t2)) + r * np.sin(t2)
y_involute_cycloid = r * (1 - np.cos(t2)) + r * (1 - np.cos(t2))


plt.figure(figsize=(10, 6))


plt.plot(x_cycloid, y_cycloid, label='Cicloide', color='blue')
plt.plot(x_involute_cycloid, y_involute_cycloid, label='Involuta (otra cicloide)', color='orange')


plt.xlabel('x')
plt.ylabel('y')
plt.title('Cicloide y (otra cicloide)')


plt.legend()

plt.grid(True)


plt.show()

#A simple vista puedo decir que ambas curvas tienen la misma forma general, pero la involuta es una réplica desplazada de la cicloide original.