# -*- coding: utf-8 -*-
"""involuta de epicicloide.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1axfMgLTielp-JjxnieFUjWE44iGzGSRe
"""

import numpy as np
import matplotlib.pyplot as plt


R = 7
r = 3

theta = np.linspace(0, 2 * np.pi, 1000)
x_epicycloid = (R + r) * np.cos(theta) - r * np.cos((R + r) / r * theta)
y_epicycloid = (R + r) * np.sin(theta) - r * np.sin((R + r) / r * theta)


t = np.linspace(0, 2 * np.pi, 1000)
x_involute_epicycloid = (R + r) * (np.cos(t) + t * np.sin(t)) - r * (np.cos((R + r) / r * t) + t * np.sin((R + r) / r * t))
y_involute_epicycloid = (R + r) * (np.sin(t) - t * np.cos(t)) - r * (np.sin((R + r) / r * t) - t * np.cos((R + r) / r * t))



plt.plot(x_epicycloid, y_epicycloid, label='Epicicloide')
plt.plot(x_involute_epicycloid, y_involute_epicycloid, label='Involuta de la epicicloide')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Epicicloide y su involuta')
plt.legend()

plt.grid(True)
plt.show()


#Analizando la grafica puedo decir que la epicicloide y su involuta nos dan formas onduladas y repetitivas, pero la involuta aparece más comprimida o desplazada en comparación con la epicicloide original.