# -*- coding: utf-8 -*-
"""involuta del circulo (espiral).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_UPFWFowGfpg4qecYbJ9O9A8zrALQlIm
"""

import numpy as np
import matplotlib.pyplot as plt


r = 1

# puntos para el círculo
theta = np.linspace(0, 2 * np.pi, 1000)
x_circle = r * np.cos(theta)
y_circle = r * np.sin(theta)

# puntos para la espiral
t = np.linspace(0, 4 * np.pi, 1000)
x_spiral = r * (np.cos(t) + t * np.sin(t))
y_spiral = r * (np.sin(t) - t * np.cos(t))


plt.figure(figsize=(10, 6))


plt.plot(x_circle, y_circle, label='Círculo', color='blue')
plt.plot(x_spiral, y_spiral, label='Espiral', color='orange')


plt.xlabel('x')
plt.ylabel('y')
plt.title('Círculo y (espiral)')

plt.legend()

plt.grid(True)


plt.show()

#revisando las curvas diria que el  círculo es una curva cerrada simple, mientras que la involuta (espiral) se extiende hacia afuera indefinidamente.