# -*- coding: utf-8 -*-
"""involuta de la elipse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZeHJCfBRHLtM6aH4ohueg2djYrTxY2U
"""

import numpy as np
import matplotlib.pyplot as plt


a = 2
b = 1

t = np.linspace(0, 8 * np.pi, 1000)
x_ellipse = a * np.cos(t)
y_ellipse = b * np.sin(t)


theta = np.linspace(0, 8 * np.pi, 1000)
x_involute_ellipse = a * (np.cos(theta) + theta * np.sin(theta))
y_involute_ellipse = b * (np.sin(theta) - theta * np.cos(theta))


plt.figure(figsize=(10, 6))


plt.plot(x_ellipse, y_ellipse, label='Elipse', color='blue')
plt.plot(x_involute_ellipse, y_involute_ellipse, label='Involuta de la elipse', color='orange')


plt.xlabel('x')
plt.ylabel('y')
plt.title('Elipse y su involuta')

plt.legend()

plt.grid(True)


plt.show()


#Observando las graficas deduje que la elipse es una curva cerrada simétrica respecto a sus ejes, mientras que su involuta es una curva abierta que se aleja de la elipse.